[package]
name = "vigil-server"
version = "1.9.0"
description = "Microservices Status Page. Monitors a distributed infrastructure and sends alerts to Slack."
readme = "README.md"
license = "MPL-2.0"
edition = "2018"
homepage = "https://github.com/valeriansaliou/vigil"
repository = "https://github.com/valeriansaliou/vigil.git"
keywords = ["microservices", "infrastructure", "status", "monitor", "slack"]
categories = ["web-programming"]
authors = ["Valerian Saliou <valerian@valeriansaliou.name>"]
exclude = ["dev/*"]

[badges]
travis-ci = { repository = "valeriansaliou/vigil", branch = "master" }
coveralls = { repository = "valeriansaliou/vigil", branch = "master", service = "github" }

[[bin]]
name = "vigil"
path = "src/main.rs"
doc = false

[dependencies]
log = "0.4"
clap = { version = "2.29", default-features = false }
lazy_static = "1.0"
time = "0.1"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
base64 = "0.10"
regex = "1.0"
url = { version = "1.6", default-features = false }
url_serde = { version = "0.2", default-features = false }
indexmap = { version = "1.0", features = ["serde-1"] }
rocket = { version = "0.4", default-features = false }
rocket_contrib = { version = "0.4", features = ["tera_templates"] }
native-tls = "0.1"
openssl-probe = "0.1"
reqwest = "0.9"
lettre = { version = "0.9.2", features = ["smtp-transport"], optional = true }
lettre_email = { version = "0.9.2", optional = true }
libstrophe = { version = "0.10", default-features = false, optional = true }

[features]
default = ["notifier-email", "notifier-twilio", "notifier-slack"]
notifier-email = ["lettre", "lettre_email"]
notifier-twilio = []
notifier-slack = []
notifier-xmpp = ["libstrophe"]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true

[profile.release]
opt-level = "s"
lto = true
debug = false
debug-assertions = false
